name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write
    issues: write
    pull-requests: write
    packages: write

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Run ESLint
              run: bunx eslint . --ext .ts

            - name: Run Prettier check
              run: bunx prettier --check .

    build-and-test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Generate Prisma Client
              run: bunx prisma generate

            - name: Build project
              run: bun run build

            - name: Copy generated Prisma client to dist
              run: |
                  mkdir -p dist/generated
                  cp -r src/generated/* dist/generated/

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/setup-buildx-action@v3

            - name: Build and Push Docker Image to GHCR
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/worlditsocialnetwork-backend:latest

    release:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"

            - name: Install dependencies (for semantic-release only)
              run: npm ci

            - name: Run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run release
